services:
  - type: web
    name: dc-music
    runtime: python
    buildCommand: bash ./build.sh
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 8080
      - key: COOKIES
        sync: false  # 這表示這是一個秘密值
    healthCheckPath: /health
    plan: free